addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.18")
resolvers += Resolver.bintrayRepo("kamon-io", "sbt-plugins")
addSbtPlugin("io.kamon" % "sbt-aspectj-runner" % "1.1.2")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.5")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
